version = 0.1
[default.deploy.parameters]
stack_name = "lambda-upload-s3"
resolve_s3 = true
s3_prefix = "lambda-upload-s3"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
